#!/usr/bin/env ruby
if ARGV.empty?
  STDERR.puts "USAGE: #{$0} <LIST OF SHAs>"
  exit
end

branch_name = %x{git branch | grep '*' | awk '{ print $2 }'}.chomp
if branch_name == "master"
  STDERR.puts "Cannot build all the things for the master branch"
  exit
end

system("git push origin #{branch_name}")
ARGV.map {|arg| arg.split(" ")}.flatten.map(&:strip).reverse.each.with_index do |ref, i|
  tmp_branch_name = "#{branch_name}-#{i}"
  puts tmp_branch_name
  system("git checkout -b #{tmp_branch_name} #{ref}")
  system("git push origin #{tmp_branch_name}")
  sleep 60
end
system("git checkout #{branch_name}")
